// let shoes = [
//     {title: 'Mesh & Grosgrain', designer:'Chanel', price: '€1100', category: 'shoes', color: 'black', size: [36, 37, 38, 39, 40], image: 'https://www.chanel.com/images/t_fashionzoom1/f_jpg/slingbacks-black-mesh-grosgrain-mesh-grosgrain-packshot-default-g34702y5027594305-8811022450718.jpg', sale: false},
//     {title: 'Calfskin & Grosgrain', designer:'Chanel', price: '€925', category: 'shoes', color: 'beige', size: [36, 37, 38, 39, 40], image: 'https://www.chanel.com/images/t_fashionzoom1/f_jpg/pumps-beige-black-calfskin-grosgrain-calfskin-grosgrain-packshot-default-g31983y51674c0204-8808872738846.jpg', sale: false},
//     {title: 'Patent Calfskin', designer:'Chanel', price: '€900', category: 'shoes', color: 'beige', size: [36, 37, 38, 39, 40], image: 'https://www.chanel.com/images/t_fashion/q_auto,f_jpg,fl_lossy,dpr_2/w_1920/pumps-beige-patent-calfskin-patent-calfskin-packshot-default-g34358x511170f600-8808849965086.jpg', sale: false},
//     {title: 'Decollete 554 vernice', designer:'Christian Louboutin', price: '€500', category: 'shoes', color: 'black', size: [36, 37, 38, 39, 40], image: 'http://images.eu.christianlouboutin.com/media/catalog/product/cache/2/thumbnail/1200x/602f0fa2c1f0d1ba5e241f914e856ff9/3/1/0/0/christianlouboutin-ladypeep-3100893_bk01_2_1200x1200_1511946036.jpg', sale: false},
//     {title: 'Romy 85', designer:'Jimmy Choo', price: '€500', category: 'shoes', color: 'blue', size: [36, 37, 38, 39, 40], image: 'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dweca6cf44/images/original/ROMY85SUE_040014_SIDE_.jpg?sw=1800&sh=1800&sm=fit', sale: false},
//     // SHOULD IT BE IN DB FILE OR HERE??????
// ]
let bags = [
    {title: 'Cluny BB', designer:'Louis Vuitton', price: '€1660', description: 'Lambskin & Gold-Tone Metal Shop Chanel Designer, visionary, artist - Gabrielle ‘Coco’ CHANEL reinvented fashion by transcending its conventions, creating an uncomplicated luxury that changed women’s lives forever. She followed no rules, epitomising the very modern values of freedom, passion and feminine elegance. “Fashion passes, style remains...” This simple statement captures the essence of her revolutionary contribution to culture. CHANEL continues, after almost a century, to inspire women of all ages all over the world with its timeless modernity.', category: 'bags', color: 'blue', img: 'https://images.harrods.com/product/gucci/mini-marmont-matelasse-shoulder-bag_000000000005365165.jpg', sale: false, _id:0},
    {title: 'Flap Bag', designer:'Chanel', price: '€3500', description: 'Lambskin & Gold-Tone Metal Shop Chanel Designer, visionary, artist - Gabrielle ‘Coco’ CHANEL reinvented fashion by transcending its conventions, creating an uncomplicated luxury that changed women’s lives forever. She followed no rules, epitomising the very modern values of freedom, passion and feminine elegance. “Fashion passes, style remains...” This simple statement captures the essence of her revolutionary contribution to culture. CHANEL continues, after almost a century, to inspire women of all ages all over the world with its timeless modernity.', category: 'bags', color: 'white', img: 'https://www.chanel.com/images/t_fashion/q_auto,f_jpg,fl_lossy,dpr_2/w_1920/flap-bag-white-lambskin-gold-tone-metal-lambskin-gold-tone-metal-packshot-default-as0321b0012010601-8811046043678.jpg', sale: false, _id:0},
    {title: 'Drawstring Bag', designer:'Chanel', price: '€4000', description: 'Lambskin & Gold-Tone Metal Shop Chanel Designer, visionary, artist - Gabrielle ‘Coco’ CHANEL reinvented fashion by transcending its conventions, creating an uncomplicated luxury that changed women’s lives forever. She followed no rules, epitomising the very modern values of freedom, passion and feminine elegance. “Fashion passes, style remains...” This simple statement captures the essence of her revolutionary contribution to culture. CHANEL continues, after almost a century, to inspire women of all ages all over the world with its timeless modernity.', category: 'bags', color: 'white', img: 'https://www.chanel.com/images/t_fashion/q_auto,f_jpg,fl_lossy,dpr_2/w_1240/drawstring-bag-white-grained-calfskin-gold-tone-metal-grained-calfskin-gold-tone-metal-packshot-default-as0310b0017010601-8812985843742.jpg', sale: false, _id:1},
    {title: 'Boy Handbag', designer:'Chanel', price: '€4200', description: 'Lambskin & Gold-Tone Metal Shop Chanel Designer, visionary, artist - Gabrielle ‘Coco’ CHANEL reinvented fashion by transcending its conventions, creating an uncomplicated luxury that changed women’s lives forever. She followed no rules, epitomising the very modern values of freedom, passion and feminine elegance. “Fashion passes, style remains...” This simple statement captures the essence of her revolutionary contribution to culture. CHANEL continues, after almost a century, to inspire women of all ages all over the world with its timeless modernity.', category: 'bags', color: 'red', img: 'https://www.chanel.com/images//t_fashion//q_auto,f_jpg,fl_lossy,dpr_2/w_1240/boy-chanel-handbag-red-calfskin-gold-tone-metal-calfskin-gold-tone-metal-packshot-default-as0130y25569n0413-8811049484318.jpg', sale: false, _id:2},
    {title: 'Small Boy Handbag', designer:'Chanel', price: '€6900', description: 'Lambskin & Gold-Tone Metal Shop Chanel Designer, visionary, artist - Gabrielle ‘Coco’ CHANEL reinvented fashion by transcending its conventions, creating an uncomplicated luxury that changed women’s lives forever. She followed no rules, epitomising the very modern values of freedom, passion and feminine elegance. “Fashion passes, style remains...” This simple statement captures the essence of her revolutionary contribution to culture. CHANEL continues, after almost a century, to inspire women of all ages all over the world with its timeless modernity.', category: 'bags', color: 'black', img: 'https://www.chanel.com/images/t_fashion/q_auto,f_jpg,fl_lossy,dpr_2/w_1240/small-boy-chanel-handbag-black-embroidered-lambskin-gold-tone-metal-embroidered-lambskin-gold-tone-metal-packshot-default-a67085b0023194305-8811054596126.jpg', sale: false, _id:3},
    {title: 'Flower zipped tote MM', designer:'Louis Vuitton', price: '€1650', description: 'Lambskin & Gold-Tone Metal Shop Chanel Designer, visionary, artist - Gabrielle ‘Coco’ CHANEL reinvented fashion by transcending its conventions, creating an uncomplicated luxury that changed women’s lives forever. She followed no rules, epitomising the very modern values of freedom, passion and feminine elegance. “Fashion passes, style remains...” This simple statement captures the essence of her revolutionary contribution to culture. CHANEL continues, after almost a century, to inspire women of all ages all over the world with its timeless modernity.', category: 'bags', color: 'brown', img: 'https://uk.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-flower-zipped-tote-mm-monogram-canvas-handbags--M44347_PM2_Front%20view.jpg?wid=1268&hei=1268', sale: false, _id:4},
    {title: 'Saintonge', designer:'Louis Vuitton', price: '€1120', description: 'Lambskin & Gold-Tone Metal Shop Chanel Designer, visionary, artist - Gabrielle ‘Coco’ CHANEL reinvented fashion by transcending its conventions, creating an uncomplicated luxury that changed women’s lives forever. She followed no rules, epitomising the very modern values of freedom, passion and feminine elegance. “Fashion passes, style remains...” This simple statement captures the essence of her revolutionary contribution to culture. CHANEL continues, after almost a century, to inspire women of all ages all over the world with its timeless modernity.', category: 'bags', color: 'brown', img: 'https://uk.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-saintonge-monogram-canvas-handbags--M43556_PM2_Front%20view.jpg?wid=1266&hei=1266', sale: false, _id:5},

    {title: 'Cluny BB', designer:'Louis Vuitton', price: '€1660', description: 'Épi inspires Nicolas...', category: 'bags', color: 'blue', img: 'https://uk.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis-vuitton-cluny-bb-epi-leather-handbags--M52868_PM2_Front%20view.jpg?wid=1268&hei=1268', sale: false},
    {title: 'Small Leather Soho Disco Bag', designer:'Gucci', price: '€890', description: 'Perfectly poised to fit your everyday essentials, the Soho disco bag from Gucci has been crafted in grained leather and boasts a chic zip-around design with the signature tassel zip pull and stitched interlocking GG logo.', category: 'bags', color: 'brown', img: 'https://images.harrods.com/product/gucci/small-leather-soho-disco-bag_000000000005422753.jpg', sale: false},
    {title: 'Mini Fayne Backpack', designer:'Chloé', price: '€1090', description: 'hloé reimagines the unmistakable Faye bag into a backpack silhouette. Channelling \'70s style in smooth leather and sumptuous suede, the convertible straps keep styling versatile while the expandable sides create extra space when you need it.', category: 'bags', color: 'black', img: 'https://images.harrods.com/product/chloe/mini-faye-backpack_000000000005427592.jpg', sale: false},
    {title: 'Small Leather Sicily Bag', designer:'Dolce & Gabbana', price: '€1095', description: 'A timeless, iconic top handle bag from Italian stalwarts, Dolce & Gabbana, the Siciliy bag is crafted Dauphine leather with gleaming gold-tone hardware. ', category: 'bags', color: 'green', img: 'https://images.harrods.com/product/dolce-and-gabbana/small-leather-sicily-bag_000000000005152338.jpg', sale: false},
    {title: 'GG Blooms Dionysus Wallet Bag', designer:'Gucci', price: '€960', description: 'Inspired by the Greek god Dionysus - said to have crossed the river Tigris on a tiger sent by Zeus - this Gucci bag is an investment in timeless Italian style.', category: 'bags', color: 'brown', img: 'https://images.harrods.com/product/gucci/gg-blooms-dionysus-wallet-bag_000000000005269686.jpg', sale: false},

]

// let oldshoes=[
//     {category:'Shoes',ttle:'MIMI 100',description:'Black Suede Wrap Around Sandals', designer:'Jimmy Choo',style:'Sandal', price:'650', size:[33, color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Mesh & Grosgrain',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Chanel',style:'Sandal', price:'970', size:'33', color:'black', img:'https://www.chanel.com/images/q_auto,f_auto,fl_lossy,dpr_auto/w_370/slingbacks-black-mesh-grosgrain-mesh-grosgrain-packshot-default-g34702y5027594305-8811022450718.jpg', sale:false},
//     {category:'Shoes',name:'Suede Goatskin',description:'Ref.  G34381 X47793 51225, ', designer:'Chanel', style:'Sandal', price:'1200', size:'33', color:'beige', img:'https://www.chanel.com/images/t_fashion/q_auto,f_jpg,fl_lossy,dpr_2/w_1680/sandals-beige-suede-goatskin-suede-goatskin-packshot-default-g34381x4779351225-8811043487774.jpg', sale:'false'},
//     {category:'Shoes',name:'Lady Peep Patent Calf',description:'An iconic model, the Lady Peep seduces with its sculptural audacity. In black patent calf leather, it is mounted on a platform and a 150mm stiletto. Its scooped lines reveal with finesse a vertiginous arch. Each step attests to the savoir-faire of the Louboutin House.', designer:'Christian Louboutin',style:'Sandal', price:'695', size:'33', color:'black', img:'http://images.eu.christianlouboutin.com/media/catalog/product/cache/2/thumbnail/1200x/602f0fa2c1f0d1ba5e241f914e856ff9/3/1/0/0/christianlouboutin-ladypeep-3100893_bk01_2_1200x1200_1511946036.jpg', sale:'false'},
//     {category:'Shoes',name:'MISTY 120',description:'Black Suede Platform Sandals', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dwda5a3c05/images/original/MISTY120SUE_010003_SIDE.jpg?sw=520&sh=520&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'},
//     {category:'Shoes',name:'Black Suede Wrap Around Sandals',description:'The Mimi sandal in black suede is the epitome of minimalist evening style. The intertwined ankle strap twists twice around the foot to create the illusion of volume and then meets in a delicate metal buckle fastening. Wear to your next dinner party or evening outing. ', designer:'Jimmy Choo',style:'Sandal', price:'650', size:'33', color:'black', img:'https://row.jimmychoo.com/dw/image/v2/AAWE_PRD/on/demandware.static/-/Sites-jch-master-product-catalog/default/dw44dc57d1/images/original/MIMI100SUE_010003_SIDE.jpg?sw=1800&sh=1800&sm=fit', sale:'false'}
// ]
module.exports = {bags}